### ISSUE TITLE
Error training dysdf models: 'DySDF' object has no attribute 'estimate_normals'

### ISSUE THREAD

**Issue by tim-depthkit** [markomih/ResFields#2]
Trying to run the [Dynamic NeRF from 4 RGB views](https://github.com/markomih/ResFields/blob/master/docs/benchmark.md#dynamic-nerf-from-4-rgb-views) benchmark. I get the following errors for all of the scenes:

```
 python launch.py --config ./configs/dysdf/base.yaml dataset.scene=dancer --exp_dir ../exp_owlii_benchmark --train model.sdf_net.resfield_layers=[1,2,3,4,5,6,7] tag=ResFields1234567
C:\Users\tim\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torchaudio\backend\utils.py:62: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Global seed set to 42
ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
Traceback (most recent call last):
  File "C:\Users\tim\repos\ResFields\dyrecon\launch.py", line 127, in <module>
    main()
  File "C:\Users\tim\repos\ResFields\dyrecon\launch.py", line 71, in main
    system = systems.make(config.system.name, config, resume_from_checkpoint)
  File "C:\Users\tim\repos\ResFields\dyrecon\systems\__init__.py", line 13, in make
    system = systems[name](config)
  File "C:\Users\tim\repos\ResFields\dyrecon\systems\base.py", line 17, in __init__
    self.model = models.make(self.config.model.name, self.config.model)
  File "C:\Users\tim\repos\ResFields\dyrecon\models\__init__.py", line 12, in make
    model = models[name](config)
  File "C:\Users\tim\repos\ResFields\dyrecon\models\base.py", line 12, in __init__
    self.setup()
  File "C:\Users\tim\repos\ResFields\dyrecon\models\dysdf.py", line 53, in setup
    self.estimate_normals = self.estimate_normals in ['volsdf', 'neus']
  File "C:\Users\tim\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DySDF' object has no attribute 'estimate_normals'
```

Any ideas?

**Comment by markomih** [comment]
Hi @tim-depthkit, thank you for reporting the issue. 
Indeed the estimate_normals variable was a typo in [L63](https://github.com/markomih/ResFields/blob/master/dyrecon/models/dysdf.py#L53C14-L53C30). Please pull the latest commit.
